
create database if not exists bobo_beats;

use bobo_beats;

drop table if exists users;

create table users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  avatar_url VARCHAR(128) NOT NULL,
  followerCount INT
);

INSERT INTO users 
  (username, avatar_url, followerCount) VALUES
("Ivy Carter", "https://s3.amazonaws.com/uifaces/faces/twitter/koridhandy/128.jpg", 9),
("Ashly Treutel", "https://s3.amazonaws.com/uifaces/faces/twitter/fiterik/128.jpg", 94),
("Carmen Skiles", "https://s3.amazonaws.com/uifaces/faces/twitter/myastro/128.jpg", 82),
("Oswald Mueller", "https://s3.amazonaws.com/uifaces/faces/twitter/sawrb/128.jpg", 19),
("Wade Corkery", "https://s3.amazonaws.com/uifaces/faces/twitter/carbontwelve/128.jpg", 76),
("Ricky Kovacek", "https://s3.amazonaws.com/uifaces/faces/twitter/daniloc/128.jpg", 39),
("Darius Cremin", "https://s3.amazonaws.com/uifaces/faces/twitter/ajaxy_ru/128.jpg", 40),
("Moises Schimmel", "https://s3.amazonaws.com/uifaces/faces/twitter/ashernatali/128.jpg", 5),
("Nora Cummerata", "https://s3.amazonaws.com/uifaces/faces/twitter/wim1k/128.jpg", 63),
("Tito Schmidt", "https://s3.amazonaws.com/uifaces/faces/twitter/cyril_gaillard/128.jpg", 61),
("Zackery Johns", "https://s3.amazonaws.com/uifaces/faces/twitter/thekevinjones/128.jpg", 83),
("Thad Quitzon", "https://s3.amazonaws.com/uifaces/faces/twitter/baumannzone/128.jpg", 55),
("Dean Stoltenberg", "https://s3.amazonaws.com/uifaces/faces/twitter/reabo101/128.jpg", 14),
("Yoshiko Bernier", "https://s3.amazonaws.com/uifaces/faces/twitter/jacksonlatka/128.jpg", 96),
("Bertram Pfannerstill", "https://s3.amazonaws.com/uifaces/faces/twitter/noufalibrahim/128.jpg", 79),
("Wellington Crona", "https://s3.amazonaws.com/uifaces/faces/twitter/eugeneeweb/128.jpg", 4),
("Elnora Roob", "https://s3.amazonaws.com/uifaces/faces/twitter/kurtinc/128.jpg", 28),
("Hester Rutherford", "https://s3.amazonaws.com/uifaces/faces/twitter/jarjan/128.jpg", 30),
("Annette Walsh", "https://s3.amazonaws.com/uifaces/faces/twitter/abdulhyeuk/128.jpg", 20),
("Gisselle Muller", "https://s3.amazonaws.com/uifaces/faces/twitter/guiiipontes/128.jpg", 35),
("Zoila Fay", "https://s3.amazonaws.com/uifaces/faces/twitter/mds/128.jpg", 17),
("Maegan Stiedemann", "https://s3.amazonaws.com/uifaces/faces/twitter/calebogden/128.jpg", 7),
("Tiana Dickens", "https://s3.amazonaws.com/uifaces/faces/twitter/danvernon/128.jpg", 0),
("Kamille Maggio", "https://s3.amazonaws.com/uifaces/faces/twitter/vladarbatov/128.jpg", 58),
("Rylan Stark", "https://s3.amazonaws.com/uifaces/faces/twitter/justinrgraham/128.jpg", 15),
("Stephanie Lesch", "https://s3.amazonaws.com/uifaces/faces/twitter/danthms/128.jpg", 54),
("Colin Jaskolski", "https://s3.amazonaws.com/uifaces/faces/twitter/low_res/128.jpg", 48),
("Olin Pollich", "https://s3.amazonaws.com/uifaces/faces/twitter/pehamondello/128.jpg", 91),
("Ebony Johns", "https://s3.amazonaws.com/uifaces/faces/twitter/jackiesaik/128.jpg", 11),
("Ardella Gleichner", "https://s3.amazonaws.com/uifaces/faces/twitter/mbilalsiddique1/128.jpg", 2),
("Zachariah Roob", "https://s3.amazonaws.com/uifaces/faces/twitter/poormini/128.jpg", 55),
("Jerrell Bartoletti", "https://s3.amazonaws.com/uifaces/faces/twitter/fronx/128.jpg", 25),
("Audra Volkman", "https://s3.amazonaws.com/uifaces/faces/twitter/jeremiespoken/128.jpg", 41),
("Friedrich Runolfsdottir", "https://s3.amazonaws.com/uifaces/faces/twitter/posterjob/128.jpg", 50),
("Dusty Lakin", "https://s3.amazonaws.com/uifaces/faces/twitter/emmandenn/128.jpg", 92),
("Lafayette Hamill", "https://s3.amazonaws.com/uifaces/faces/twitter/itstotallyamy/128.jpg", 78),
("Hudson Larson", "https://s3.amazonaws.com/uifaces/faces/twitter/krasnoukhov/128.jpg", 83),
("Nyasia Corkery", "https://s3.amazonaws.com/uifaces/faces/twitter/mgonto/128.jpg", 7),
("Hettie Cremin", "https://s3.amazonaws.com/uifaces/faces/twitter/tumski/128.jpg", 54),
("Alexandro Morar", "https://s3.amazonaws.com/uifaces/faces/twitter/mrebay007/128.jpg", 24),
("Shaylee Murazik", "https://s3.amazonaws.com/uifaces/faces/twitter/iqbalperkasa/128.jpg", 96),
("Cletus Moore", "https://s3.amazonaws.com/uifaces/faces/twitter/ky/128.jpg", 31),
("Gerson Robel", "https://s3.amazonaws.com/uifaces/faces/twitter/anthonysukow/128.jpg", 80),
("Grayson Runte", "https://s3.amazonaws.com/uifaces/faces/twitter/johannesneu/128.jpg", 56),
("Ruth Robel", "https://s3.amazonaws.com/uifaces/faces/twitter/alexivanichkin/128.jpg", 91),
("Sandra Bernhard", "https://s3.amazonaws.com/uifaces/faces/twitter/wiljanslofstra/128.jpg", 51),
("Elsa Eichmann", "https://s3.amazonaws.com/uifaces/faces/twitter/longlivemyword/128.jpg", 74),
("Americo Howe", "https://s3.amazonaws.com/uifaces/faces/twitter/madcampos/128.jpg", 47),
("Jarod Dare", "https://s3.amazonaws.com/uifaces/faces/twitter/xripunov/128.jpg", 0),
("Eldridge Mayert", "https://s3.amazonaws.com/uifaces/faces/twitter/chrisstumph/128.jpg", 59),
("Cielo Cole", "https://s3.amazonaws.com/uifaces/faces/twitter/tgerken/128.jpg", 44),
("Katelin Walsh", "https://s3.amazonaws.com/uifaces/faces/twitter/a1chapone/128.jpg", 28),
("Fleta Stehr", "https://s3.amazonaws.com/uifaces/faces/twitter/ariffsetiawan/128.jpg", 82),
("Beatrice Dietrich", "https://s3.amazonaws.com/uifaces/faces/twitter/mtolokonnikov/128.jpg", 34),
("Eugenia Balistreri", "https://s3.amazonaws.com/uifaces/faces/twitter/9lessons/128.jpg", 92),
("Nathan Feeney", "https://s3.amazonaws.com/uifaces/faces/twitter/chanpory/128.jpg", 88),
("Elva Hoeger", "https://s3.amazonaws.com/uifaces/faces/twitter/yalozhkin/128.jpg", 58),
("Charlie Schoen", "https://s3.amazonaws.com/uifaces/faces/twitter/pcridesagain/128.jpg", 49),
("Leanna Leannon", "https://s3.amazonaws.com/uifaces/faces/twitter/el_fuertisimo/128.jpg", 16),
("Diego Boyer", "https://s3.amazonaws.com/uifaces/faces/twitter/davidsasda/128.jpg", 52),
("Cheyanne Hudson", "https://s3.amazonaws.com/uifaces/faces/twitter/xiel/128.jpg", 81),
("Alfonso Altenwerth", "https://s3.amazonaws.com/uifaces/faces/twitter/dev_essentials/128.jpg", 46),
("Berenice Champlin", "https://s3.amazonaws.com/uifaces/faces/twitter/wearesavas/128.jpg", 32),
("Abdul Lebsack", "https://s3.amazonaws.com/uifaces/faces/twitter/BenouarradeM/128.jpg", 21),
("Boyd Donnelly", "https://s3.amazonaws.com/uifaces/faces/twitter/josep_martins/128.jpg", 42),
("Baby Farrell", "https://s3.amazonaws.com/uifaces/faces/twitter/ryanmclaughlin/128.jpg", 62),
("Allie Kemmer", "https://s3.amazonaws.com/uifaces/faces/twitter/reideiredale/128.jpg", 97),
("Jules Koelpin", "https://s3.amazonaws.com/uifaces/faces/twitter/saarabpreet/128.jpg", 10),
("Evan Brekke", "https://s3.amazonaws.com/uifaces/faces/twitter/lawlbwoy/128.jpg", 0),
("Olaf Kilback", "https://s3.amazonaws.com/uifaces/faces/twitter/sprayaga/128.jpg", 45),
("Edwardo Daugherty", "https://s3.amazonaws.com/uifaces/faces/twitter/ntfblog/128.jpg", 1),
("Alan Rodriguez", "https://s3.amazonaws.com/uifaces/faces/twitter/loganjlambert/128.jpg", 33),
("Tressie Howe", "https://s3.amazonaws.com/uifaces/faces/twitter/myastro/128.jpg", 74),
("Dillan Schoen", "https://s3.amazonaws.com/uifaces/faces/twitter/baumann_alex/128.jpg", 99),
("Derick Cormier", "https://s3.amazonaws.com/uifaces/faces/twitter/tom_even/128.jpg", 87),
("Bridgette Davis", "https://s3.amazonaws.com/uifaces/faces/twitter/sovesove/128.jpg", 8),
("Nettie Simonis", "https://s3.amazonaws.com/uifaces/faces/twitter/tonymillion/128.jpg", 89),
("Moses Yost", "https://s3.amazonaws.com/uifaces/faces/twitter/nerrsoft/128.jpg", 97),
("Armand Grant", "https://s3.amazonaws.com/uifaces/faces/twitter/privetwagner/128.jpg", 3),
("Arely Goyette", "https://s3.amazonaws.com/uifaces/faces/twitter/karlkanall/128.jpg", 66),
("Ryder Bartoletti", "https://s3.amazonaws.com/uifaces/faces/twitter/josep_martins/128.jpg", 96),
("Brisa Grady", "https://s3.amazonaws.com/uifaces/faces/twitter/dnirmal/128.jpg", 13),
("Fritz Cormier", "https://s3.amazonaws.com/uifaces/faces/twitter/_ragzor/128.jpg", 19),
("Chris Jerde", "https://s3.amazonaws.com/uifaces/faces/twitter/lawlbwoy/128.jpg", 86),
("Wilton Johnston", "https://s3.amazonaws.com/uifaces/faces/twitter/doronmalki/128.jpg", 47),
("Jaron Dickinson", "https://s3.amazonaws.com/uifaces/faces/twitter/wake_gs/128.jpg", 84),
("Eino Streich", "https://s3.amazonaws.com/uifaces/faces/twitter/josevnclch/128.jpg", 30),
("Bo Bailey", "https://s3.amazonaws.com/uifaces/faces/twitter/chris_witko/128.jpg", 27),
("Jarrett Mraz", "https://s3.amazonaws.com/uifaces/faces/twitter/robturlinckx/128.jpg", 18),
("Archibald Weber", "https://s3.amazonaws.com/uifaces/faces/twitter/sainraja/128.jpg", 73),
("Cristian Padberg", "https://s3.amazonaws.com/uifaces/faces/twitter/incubo82/128.jpg", 57),
("Timmothy Treutel", "https://s3.amazonaws.com/uifaces/faces/twitter/johnsmithagency/128.jpg", 59),
("Coby Feeney", "https://s3.amazonaws.com/uifaces/faces/twitter/buddhasource/128.jpg", 40),
("Bart Rohan", "https://s3.amazonaws.com/uifaces/faces/twitter/oktayelipek/128.jpg", 58),
("Burdette Turner", "https://s3.amazonaws.com/uifaces/faces/twitter/marciotoledo/128.jpg", 39),
("Ryder Daniel", "https://s3.amazonaws.com/uifaces/faces/twitter/mr_shiznit/128.jpg", 8),
("Al Boyer", "https://s3.amazonaws.com/uifaces/faces/twitter/rikas/128.jpg", 12),
("Ellsworth Metz", "https://s3.amazonaws.com/uifaces/faces/twitter/antjanus/128.jpg", 4),
("Bret Lehner", "https://s3.amazonaws.com/uifaces/faces/twitter/markretzloff/128.jpg", 42),
("Weldon Koch", "https://s3.amazonaws.com/uifaces/faces/twitter/lhausermann/128.jpg", 43);